# Generated by Django 5.2.6 on 2025-09-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Forms',
        ),
    ]
