# Generated by Django 5.2.6 on 2025-09-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
